title: Chants at The Abbey
author: Friar Buck
email: sailingcomputergeek@yahoo.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  The Abbey is the home of a group of dedicated monks who strive for 
  a better understanding of the Universe through manipulation of 
  programming code. Please join us in our chants.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  sailingcomputergeek # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
